@startuml Conspiracy Graph
left to right direction
skinparam linetype polyline
skinparam nodesep 60

'Global Actors here:
actor "Berry the Manticore" as manticorBerry
actor "Brown orc (Sacred Orc)" as brownOrc
note top of brownOrc
    * knows magic?
end note
(Orcs) as orcs
(Dragons) as dragons
(Some secret organization) as secretOrg

'Global Notes
note top of dragons
    -Makes no sense
    -Only Mayor believes
    -allegedly white dragon
    -possibly just clouds
    -maybe a red herring
end note

note top of orcs
    Displaced by Manticors and other monsters
    Forming warparties
end note

' Global only relations
brownOrc --> orcs : leader?
orcs --> manticorBerry : displaced

'######### Location Phandalin #########
rectangle Phandalin {
    ' locations
    [Stone Hill Inn] as stoneHillInn
    [Townmasters Hall] as townHall
    [Smithy]
    [Destroyed Shrine to Tumorah] as shrine
    [General Store] as generalStore
    [Mayors House] as mayorsHouse
    [Miner's Exchange] as minerHall
    [Windmill (Umbrage Hill)] as Windmill

    'People / Actors with notes
    actor "Toblen Stonehill" as innkeep
    actor "Linine Graywind" as Smith
    note top of Smith
        * Hands out Weapons to townfolk
    end note
    actor "Sister Faelith" as Sister1
    actor "Unknown Sister" as Sister2
    actor "Elmar Barthen" as generalStoreGuy
    actor "Ander" as generalStoreHelper

    actor "Harbin Wester" as Mayor
    note top of Mayor
        * Mayor of Phandalin
        * Wealthy
        * Paid for Quest
    end note

    actor "Adabra Gwynn" as potionSeller
    actor "Halia Thornton" as prospectorReception
    note top of prospectorReception
        * Has some "Connections?"
        * Asked us to look into new Mayor
        * Told us about old mayor's suspicious death
        * From her notes: "Axe" supposedly important?!
    end note

    actor "Old Mayor" as oldMayor #line.dashed;line:red
    note top of oldMayor
        * Was young
        * Allegedly died of heart attack
        * Body was taken to (Waterdeep?)
    end note

    actor "Shifty Gnomes" as shiftyGnomes

    'local relations

    shiftyGnomes --> stoneHillInn : Gambled and stole from patreons
    prospectorReception --> secretOrg : part of

    innkeep --> stoneHillInn : owner
    Smith --> Smithy : owner
    Sister1 --> shrine : supporter
    Sister2 --> shrine : supporter
    generalStoreGuy --> generalStore: owner
    generalStoreHelper --> generalStore : helps in
    Mayor --> mayorsHouse : lives in
    prospectorReception --> minerHall : works at
    potionSeller --> Windmill : lives in
    Mayor --> townHall : works at

    Mayor --> generalStore : owes money to
    Mayor --> potionSeller : interested in?
    potionSeller --> Mayor : dislikes

    Mayor --> oldMayor : Replaced VERY quickly after death

    potionSeller --> generalStore : provides potions to
}

manticorBerry ---> potionSeller : attacked
orcs ---> shrine : destroyed
Mayor  --->  dragons: paranoid of

'######### Temple of Abathor #########
rectangle "Temple of Abathor"{
    (Abathor)
    note top of Abathor
        * Dwarven Deity
        * God of Wealth?
        * Mad face on statue.
    end note
    actor Dazlyn
    actor Norbis

    [Well]
    (Flare of Unknown origin) as flare

    flare -- Well
}

'######### Gnomengard #########
rectangle "Gnomengard" {
    actor "Fiblestib (lead engineer)"
    actor "Dabble Dob (lead engineer)"
    actor King1 as king1
    actor King2 as king2

    (Monster Rug) as rugMonster
    (Mushrooms)
    (Wild Magic Annomaly)
    (Mimic Attack) as mimicattack
    (Drugs!)

    note top of mimicattack
        Probably has killed one gnome (whups)
    end note

    rugMonster --> Mushrooms : made of
    rugMonster --> king1 : attacked
    mimicattack --> rugMonster : is
}

'######### Woodcutter Camp #########
rectangle "Logging Camp" as woodcutterCamp {
    actor "Tibor Wester" as woodcutterLeader
}

woodcutterLeader --- Mayor : half-brothers
Mayor ---> woodcutterCamp : wants sends provisions


'######### ??? Ranch #########
rectangle "Butterskull Ranch" as ranch {
    actor "Alfonse 'Big Al' Kalazorn" as sheriff
}

orcs ---> ranch : attacked
Mayor ---> ranch : wants investigated
'Mayor ---> sheriff : wants proof of demise?

'######### Lighthouse #########
rectangle "Lighthouse" as lighthouse {

}
note top of lighthouse
    * not in use
    * started to glow green
end note

dragons ---> lighthouse : seen by Hollis and Ahnold at

'######### Trade Route #########
(Trade Route) as tradeRoute

note top of tradeRoute
    * used to be over road
    * Over sea since 6 months
    * Provisions stopped coming recently
end note

tradeRoute --- Phandalin
Mayor ---> tradeRoute : doesnt know of problems
lighthouse ---> tradeRoute : causes shipwrecks?

'######### TNeverwinter #########
rectangle Neverwinter {
}

tradeRoute --- Neverwinter




@enduml
